spring:
  datasource:
    url: jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}